# Generated by Django 4.1.7 on 2023-06-01 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.BigIntegerField()),
                ('college', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('grad_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up1', models.DateField()),
                ('follow_up2', models.DateField()),
                ('follow_up3', models.DateField()),
                ('comments', models.CharField(max_length=200)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.student')),
            ],
        ),
    ]
