# Generated by Django 4.1.7 on 2023-06-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_followup_comments_alter_followup_follow_up1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='follow_up1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='follow_up2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='follow_up3',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='FollowUp',
        ),
    ]
