# Generated by Django 4.1.7 on 2023-06-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='follow_up1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='follow_up2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='follow_up3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
