# Generated by Django 4.1.7 on 2023-06-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_alter_student_follow_up1_alter_student_follow_up2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='follow_up1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='follow_up2',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='follow_up3',
            field=models.DateField(null=True),
        ),
    ]
